### ISSUE TITLE
Provide some basic filtering in `apilogs` route

### ISSUE THREAD

**Issue by mikeerickson** [aungwinthant/apilogger#20]
I am not so much making an issue here, but rather opening some dialog about enhancing the `apilogs` route to include some basic filtering or query functions.

I am thinking maybe allowing some sort of search functionality, or filter request type, etc.  This apilogs route could get very big and hard to navigate in a hurry.

Perhaps at a minimum, maybe show a drop-down to select the desired day in the file logger is being used (which it is in my case).  In my local usage, I was trying to track down some entries for the last couple of days of use, but it was a "massive" list already.

I suppose I could use the DB logger and navigate using TablePlus or SequelPro, but I really don't want to log to the database if I can avoid it, much rather use FileLogger

If anybody wants to chime in here, I am all ears

**Comment by aungwinthant** [comment]
Yeah.. good point. I also am thinking about adding search function. I will add it after fixing all the other issues. Thanks alot for the idea and feedback.

**Comment by mikeerickson** [comment]
No worries, again I was just thinking out loud as I have had to use the logs today to track down some issues with our API endpoints. I was accessing remotely without access to the file logs so I could only review via the route.
