### ISSUE TITLE
Save API response 

### ISSUE THREAD

**Issue by arturcorvino** [aungwinthant/apilogger#3]
It would be nice if the project saved api's response for each request as well.  Do you think it's possible?

BTW, that’s awesome!! Congrats! 🤩

**Comment by aungwinthant** [comment]
Hi, it is possible. At first, I added response. Later I replaced it with just status code because response text is very long in some cases such as an exception throws. I will try to include response content with necessary exception logics with better ui later.

**Comment by warrence** [comment]
Hi, thanks for such an awesome package. It would be really nice if we have the response logged as well, is this still happening?
