### ISSUE TITLE
Error while installing this package

### ISSUE THREAD

**Issue by IAmShafqatAli** [aungwinthant/apilogger#39]
Hi, 
I tired installing the package but I got following error. 
```
Class AWT\Http\Exceptions\InvalidApiLogDriverException located in D:/laragon/www/eazy-customs-api/vendor/awt/apilogger/src\Exceptions\InvalidApiLogDriverException.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ApiLogServiceProvider.php line 59:

  Class 'AWT\Http\Exceptions\InvalidApiLogDriverException' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by IAmShafqatAli** [comment]
> Hi,
> I tired installing the package but I got following error.
> 
> ```
> Class AWT\Http\Exceptions\InvalidApiLogDriverException located in D:/laragon/www/eazy-customs-api/vendor/awt/apilogger/src\Exceptions\InvalidApiLogDriverException.php does not comply with psr-4 autoloading standard. Skipping.
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover --ansi
> 
> In ApiLogServiceProvider.php line 59:
> 
>   Class 'AWT\Http\Exceptions\InvalidApiLogDriverException' not found
> 
> 
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> ```

`php artisan  optimize:clear ` let me solve the problem.

**Comment by soonseek** [comment]
thanks a lot.
