### ISSUE TITLE
Log file date format

### ISSUE THREAD

**Issue by mikeerickson** [aungwinthant/apilogger#4]
I am looking for a way to customize the date format in API log files?  I checked the `apilog.php` file but doesn't exist.

Personally, I would like to have same format used by Laravel logs

Eg.

`apilogger-2019-08-08.log`

or, better yet in my desired format

`api-2019-08-08.log`

Possible config entry

```php
<?php

return [
    //currently supported drivers are 'db' and 'file'
    "driver" => "file",
    "filename" => "api-yyyy-mm-dd.log"
];
```

Thinking of a quick change to `FileLogger.php:61`

```php
   $filename = 'api-'.date('Y-m-d') . '.log';
```

If you are interested, I would be happy to make a PR for this (unless you already have plans for this capability).

**Comment by aungwinthant** [comment]
Sure. Please make a PR and I will include this in coming release. Thank you for your feedback and contribution.

**Comment by mikeerickson** [comment]
Please see PR https://github.com/aungwinthant/apilogger/pull/19

Let me know if you have any questions / changes
