### ISSUE TITLE
Please Downgrade The PHP Version

### ISSUE THREAD

**Issue by jacow** [aungwinthant/apilogger#43]
Thank you for updating the log interface.
But, may you downgrade the minimum php version ?

Because many of my project using this lib on for laravel 5.5 and laravel 6.0 that using php 7.2
After you new commit, it makes this lib only available with minimum php 8 that makes me can't install it on the old version of laravel. The minimum php 8 force the developer to upgrade minimum laravel 8.0.

Please, download the php version. 
Thank you so much

**Comment by sabin-deliveryzone** [comment]
@jacow He mentioned to send email to his personal email instead of using issue tracker.
